import type {
  AttendanceRecord,
  CashTransaction,
  CommunityEvent,
  DanceClass,
  HonorRecord,
  Instructor,
  Lead,
  Member,
  MemberProgress,
  Payment,
} from "./types";

export const members: Member[] = [
  {
    id: "member-ayu",
    memberCode: "BSDS-M-0001",
    fullName: "Ayu Larasati",
    phone: "0812-1100-2401",
    email: "ayu.larasati@example.com",
    joinedAt: "2026-01-12",
    status: "Aktif",
    membershipType: "Reguler",
    currentLevel: "Beginner",
    classesTaken: 18,
    attendanceRate: 86,
    notes: "Fokus Waltz dan posture.",
  },
  {
    id: "member-raka",
    memberCode: "BSDS-M-0002",
    fullName: "Raka Pradipta",
    phone: "0812-1100-2402",
    email: "raka.pradipta@example.com",
    joinedAt: "2025-10-04",
    status: "Aktif",
    membershipType: "Private 4x",
    currentLevel: "Bronze",
    classesTaken: 34,
    attendanceRate: 92,
  },
  {
    id: "member-nadia",
    memberCode: "BSDS-M-0003",
    fullName: "Nadia Kirana",
    phone: "0812-1100-2403",
    email: "nadia.kirana@example.com",
    joinedAt: "2026-05-19",
    status: "Trial",
    membershipType: "Trial",
    currentLevel: "Foundation",
    classesTaken: 2,
    attendanceRate: 75,
  },
  {
    id: "member-bimo",
    memberCode: "BSDS-M-0004",
    fullName: "Bimo Santosa",
    phone: "0812-1100-2404",
    email: "bimo.santosa@example.com",
    joinedAt: "2025-03-27",
    status: "Cuti",
    membershipType: "Reguler",
    currentLevel: "Silver",
    classesTaken: 61,
    attendanceRate: 64,
  },
  {
    id: "member-sinta",
    memberCode: "BSDS-M-0005",
    fullName: "Sinta Maharani",
    phone: "0812-1100-2405",
    email: "sinta.maharani@example.com",
    joinedAt: "2024-08-15",
    status: "Aktif",
    membershipType: "Reguler Plus",
    currentLevel: "Gold",
    classesTaken: 82,
    attendanceRate: 94,
  },
];

export const instructors: Instructor[] = [
  {
    id: "instructor-damar",
    instructorCode: "BSDS-I-001",
    fullName: "Damar Wicaksono",
    phone: "0813-2100-4001",
    email: "damar.w@example.com",
    status: "Aktif",
    level: "Senior Instructor",
    specialties: ["Waltz", "Foxtrot", "Quickstep"],
    sessionsThisMonth: 22,
    honorDue: 12800000,
    achievementsCount: 7,
    bio: "Pelatih ballroom standar dengan pengalaman showcase dan kompetisi nasional.",
  },
  {
    id: "instructor-ratna",
    instructorCode: "BSDS-I-002",
    fullName: "Ratna Sari",
    phone: "0813-2100-4002",
    email: "ratna.sari@example.com",
    status: "Aktif",
    level: "Professional Instructor",
    specialties: ["Cha Cha", "Rumba", "Samba"],
    sessionsThisMonth: 18,
    honorDue: 9400000,
    achievementsCount: 5,
    bio: "Instruktur latin dance dengan fokus musicality dan expression.",
  },
  {
    id: "instructor-galih",
    instructorCode: "BSDS-I-003",
    fullName: "Galih Pamungkas",
    phone: "0813-2100-4003",
    email: "galih.p@example.com",
    status: "Guest instructor",
    level: "Maestro",
    specialties: ["Tango", "Social Dance"],
    sessionsThisMonth: 7,
    honorDue: 4100000,
    achievementsCount: 11,
    bio: "Guest coach untuk teknik partner work dan floorcraft.",
  },
];

export const classes: DanceClass[] = [
  {
    id: "class-waltz-beginner",
    classCode: "BSDS-C-001",
    name: "Waltz Beginner",
    type: "Kelas reguler",
    level: "Beginner",
    danceStyle: "Waltz",
    instructorName: "Damar Wicaksono",
    assistantName: "Sinta Maharani",
    day: "Selasa",
    startTime: "19:00",
    endTime: "20:30",
    room: "Studio Heritage",
    capacity: 24,
    enrolled: 19,
    price: 250000,
    status: "Aktif",
    revenueMonth: 9500000,
    attendanceRate: 88,
  },
  {
    id: "class-latin-foundation",
    classCode: "BSDS-C-002",
    name: "Latin Foundation",
    type: "Kelas reguler",
    level: "Foundation",
    danceStyle: "Cha Cha",
    instructorName: "Ratna Sari",
    day: "Kamis",
    startTime: "18:30",
    endTime: "20:00",
    room: "Studio Sangkuriang",
    capacity: 26,
    enrolled: 22,
    price: 250000,
    status: "Aktif",
    revenueMonth: 11000000,
    attendanceRate: 91,
  },
  {
    id: "class-private-raka",
    classCode: "BSDS-PC-014",
    name: "Private Bronze Technique",
    type: "Private class",
    level: "Bronze",
    danceStyle: "Foxtrot",
    instructorName: "Damar Wicaksono",
    day: "Sabtu",
    startTime: "10:00",
    endTime: "11:00",
    room: "Studio Private",
    capacity: 2,
    enrolled: 1,
    price: 450000,
    status: "Aktif",
    revenueMonth: 3600000,
    attendanceRate: 100,
  },
  {
    id: "class-social-night",
    classCode: "BSDS-C-004",
    name: "Social Dance Night Prep",
    type: "Special class",
    level: "All level",
    danceStyle: "Social Dance",
    instructorName: "Galih Pamungkas",
    day: "Jumat",
    startTime: "19:00",
    endTime: "21:00",
    room: "Pendopo",
    capacity: 40,
    enrolled: 31,
    price: 150000,
    status: "Aktif",
    revenueMonth: 4650000,
    attendanceRate: 84,
  },
];

export const attendance: AttendanceRecord[] = [
  {
    id: "att-001",
    date: "2026-06-03",
    className: "Waltz Beginner",
    memberName: "Ayu Larasati",
    instructorName: "Damar Wicaksono",
    status: "Hadir",
    checkInTime: "18:55",
    method: "QR code",
    notes: "Natural turn meningkat.",
  },
  {
    id: "att-002",
    date: "2026-06-03",
    className: "Waltz Beginner",
    memberName: "Raka Pradipta",
    instructorName: "Damar Wicaksono",
    status: "Hadir",
    checkInTime: "18:58",
    method: "Admin check-in",
  },
  {
    id: "att-003",
    date: "2026-06-05",
    className: "Latin Foundation",
    memberName: "Nadia Kirana",
    instructorName: "Ratna Sari",
    status: "Izin",
    checkInTime: "-",
    method: "Admin check-in",
    notes: "Reschedule trial.",
  },
  {
    id: "att-004",
    date: "2026-06-07",
    className: "Private Bronze Technique",
    memberName: "Raka Pradipta",
    instructorName: "Damar Wicaksono",
    status: "Hadir",
    checkInTime: "09:56",
    method: "Instruktur check-in",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-001",
    invoiceNo: "INV-2026-0601",
    payerName: "Ayu Larasati",
    category: "Kelas reguler",
    amount: 250000,
    status: "Paid",
    dueDate: "2026-06-05",
    paidAt: "2026-06-02",
    instructorShare: 200000,
    communityShare: 50000,
  },
  {
    id: "pay-002",
    invoiceNo: "INV-2026-0602",
    payerName: "Raka Pradipta",
    category: "Private class",
    amount: 1500000,
    status: "Verified",
    dueDate: "2026-06-08",
    paidAt: "2026-06-07",
    instructorShare: 1200000,
    communityShare: 300000,
  },
  {
    id: "pay-003",
    invoiceNo: "INV-2026-0603",
    payerName: "Nadia Kirana",
    category: "Trial class",
    amount: 100000,
    status: "Pending",
    dueDate: "2026-06-15",
    instructorShare: 80000,
    communityShare: 20000,
  },
  {
    id: "pay-004",
    invoiceNo: "INV-2026-0604",
    payerName: "Sinta Maharani",
    category: "Workshop",
    amount: 350000,
    status: "Paid",
    dueDate: "2026-06-12",
    paidAt: "2026-06-10",
    instructorShare: 245000,
    communityShare: 105000,
  },
];

export const transactions: CashTransaction[] = [
  {
    id: "trx-001",
    date: "2026-06-02",
    type: "Cash in",
    category: "Kas komunitas 20%",
    description: "Share kelas reguler Juni",
    amount: 50000,
  },
  {
    id: "trx-002",
    date: "2026-06-07",
    type: "Cash in",
    category: "Kas komunitas 20%",
    description: "Share private class Raka",
    amount: 300000,
  },
  {
    id: "trx-003",
    date: "2026-06-09",
    type: "Cash out",
    category: "Promosi dan Branding",
    description: "Desain poster Ballroom Night",
    amount: 450000,
  },
  {
    id: "trx-004",
    date: "2026-06-11",
    type: "Cash out",
    category: "Operasional",
    description: "Air minum dan ATK studio",
    amount: 280000,
  },
];

export const honors: HonorRecord[] = [
  {
    id: "honor-001",
    instructorName: "Damar Wicaksono",
    period: "Juni 2026",
    classCount: 2,
    sessionCount: 22,
    attendeeCount: 138,
    grossRevenue: 16000000,
    instructorShare: 12800000,
    deductions: 0,
    bonus: 400000,
    totalHonor: 13200000,
    status: "Waiting Approval",
  },
  {
    id: "honor-002",
    instructorName: "Ratna Sari",
    period: "Juni 2026",
    classCount: 1,
    sessionCount: 18,
    attendeeCount: 112,
    grossRevenue: 11750000,
    instructorShare: 9400000,
    deductions: 0,
    bonus: 250000,
    totalHonor: 9650000,
    status: "Approved",
  },
  {
    id: "honor-003",
    instructorName: "Galih Pamungkas",
    period: "Juni 2026",
    classCount: 1,
    sessionCount: 7,
    attendeeCount: 31,
    grossRevenue: 4650000,
    instructorShare: 3720000,
    deductions: 0,
    bonus: 380000,
    totalHonor: 4100000,
    status: "Paid",
  },
];

export const events: CommunityEvent[] = [
  {
    id: "event-001",
    eventCode: "EVT-2026-07",
    name: "Ballroom Night Heritage Edition",
    type: "Ballroom Night",
    date: "2026-07-12",
    time: "19:00",
    location: "Pendopo Bumi Sangkuriang",
    quota: 80,
    registered: 54,
    ticketPrice: 150000,
    status: "Open Registration",
    revenue: 8100000,
    expenses: 3600000,
  },
  {
    id: "event-002",
    eventCode: "WRK-2026-06",
    name: "Workshop Partnering & Floorcraft",
    type: "Workshop",
    date: "2026-06-29",
    time: "10:00",
    location: "Studio Heritage",
    quota: 35,
    registered: 29,
    ticketPrice: 350000,
    status: "Open Registration",
    revenue: 10150000,
    expenses: 2800000,
  },
  {
    id: "event-003",
    eventCode: "TRIAL-2026-06",
    name: "Open Trial Latin Foundation",
    type: "Trial class",
    date: "2026-06-20",
    time: "18:30",
    location: "Studio Sangkuriang",
    quota: 20,
    registered: 13,
    ticketPrice: 100000,
    status: "Open Registration",
    revenue: 1300000,
    expenses: 250000,
  },
];

export const leads: Lead[] = [
  {
    id: "lead-001",
    fullName: "Meita Rosalia",
    whatsapp: "0812-3300-5101",
    source: "Instagram",
    interestClass: "Latin Foundation",
    firstContactAt: "2026-06-10",
    status: "Trial scheduled",
    notes: "Datang trial 20 Juni.",
  },
  {
    id: "lead-002",
    fullName: "Arman Fikri",
    whatsapp: "0812-3300-5102",
    source: "Referral",
    interestClass: "Waltz Beginner",
    firstContactAt: "2026-06-09",
    status: "Contacted",
    notes: "Menunggu jadwal kerja.",
  },
  {
    id: "lead-003",
    fullName: "Livia Anindya",
    whatsapp: "0812-3300-5103",
    source: "Event",
    interestClass: "Private class",
    firstContactAt: "2026-06-08",
    status: "Interested",
    notes: "Tertarik paket private 4x.",
  },
];

export const progress: MemberProgress[] = [
  {
    id: "progress-ayu",
    memberName: "Ayu Larasati",
    currentLevel: "Beginner",
    targetLevel: "Bronze",
    progressPercent: 68,
    attendanceMonth: 85,
    masteredSkills: 12,
    totalSkills: 18,
    assessmentAverage: 3.7,
    badges: ["First Class", "10 Classes Completed", "Consistent Attendance"],
    feedback: "Posture sudah lebih stabil. Latih Natural Turn dan Reverse Turn.",
  },
  {
    id: "progress-raka",
    memberName: "Raka Pradipta",
    currentLevel: "Bronze",
    targetLevel: "Silver",
    progressPercent: 74,
    attendanceMonth: 92,
    masteredSkills: 16,
    totalSkills: 21,
    assessmentAverage: 4.1,
    badges: ["25 Classes Completed", "Bronze Achiever"],
    feedback: "Floorcraft membaik, perlu polish timing di Foxtrot.",
  },
  {
    id: "progress-sinta",
    memberName: "Sinta Maharani",
    currentLevel: "Gold",
    targetLevel: "Performance / Competition",
    progressPercent: 81,
    attendanceMonth: 94,
    masteredSkills: 24,
    totalSkills: 28,
    assessmentAverage: 4.4,
    badges: ["50 Classes Completed", "First Showcase", "Gold Achiever"],
    feedback: "Siap masuk latihan showcase internal dengan partner tetap.",
  },
];

export const monthlyCashFlow = [
  { month: "Jan", income: 18300000, expenses: 3900000, communityCash: 3660000 },
  { month: "Feb", income: 22100000, expenses: 4600000, communityCash: 4420000 },
  { month: "Mar", income: 24600000, expenses: 5200000, communityCash: 4920000 },
  { month: "Apr", income: 26800000, expenses: 6100000, communityCash: 5360000 },
  { month: "Mei", income: 31200000, expenses: 7200000, communityCash: 6240000 },
  { month: "Jun", income: 35000000, expenses: 3500000, communityCash: 7000000 },
];

